// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: game_primitives.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Spelldawn.Protos {

  /// <summary>Holder for reflection information generated from game_primitives.proto</summary>
  public static partial class GamePrimitivesReflection {

    #region Descriptor
    /// <summary>File descriptor for game_primitives.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GamePrimitivesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVnYW1lX3ByaW1pdGl2ZXMucHJvdG8SAnNkIk0KBkNhcmRJZBInCg1pZGVu",
            "dGl0eV9jYXJkGAEgASgOMg4uc2QuUGxheWVyTmFtZUgAEg8KBXZhbHVlGAIg",
            "ASgFSABCCQoHY2FyZF9pZCJOCgZSb29tSWQSIwoKaW5uZXJfcm9vbRgBIAEo",
            "DjINLnNkLklubmVyUm9vbUgAEhQKCm91dGVyX3Jvb20YAiABKAVIAEIJCgdy",
            "b29tX2lkIlIKCFRhcmdldElkEh0KB2NhcmRfaWQYASABKAsyCi5zZC5DYXJk",
            "SWRIABIdCgdyb29tX2lkGAIgASgLMgouc2QuUm9vbUlkSABCCAoGdGFyZ2V0",
            "KlkKClBsYXllck5hbWUSGwoXUExBWUVSX05BTUVfVU5TUEVDSUZJRUQQABIU",
            "ChBQTEFZRVJfTkFNRV9VU0VSEAESGAoUUExBWUVSX05BTUVfT1BQT05FTlQQ",
            "AipvCglJbm5lclJvb20SGgoWSU5ORVJfUk9PTV9VTlNQRUNJRklFRBAAEhcK",
            "E0lOTkVSX1JPT01fVFJFQVNVUlkQARIWChJJTk5FUl9ST09NX1NBTkNUVU0Q",
            "AhIVChFJTk5FUl9ST09NX0NSWVBUUxADQhOqAhBTcGVsbGRhd24uUHJvdG9z",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Spelldawn.Protos.PlayerName), typeof(global::Spelldawn.Protos.InnerRoom), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Spelldawn.Protos.CardId), global::Spelldawn.Protos.CardId.Parser, new[]{ "IdentityCard", "Value" }, new[]{ "CardId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Spelldawn.Protos.RoomId), global::Spelldawn.Protos.RoomId.Parser, new[]{ "InnerRoom", "OuterRoom" }, new[]{ "RoomId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Spelldawn.Protos.TargetId), global::Spelldawn.Protos.TargetId.Parser, new[]{ "CardId", "RoomId" }, new[]{ "Target" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PlayerName {
    [pbr::OriginalName("PLAYER_NAME_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("PLAYER_NAME_USER")] User = 1,
    [pbr::OriginalName("PLAYER_NAME_OPPONENT")] Opponent = 2,
  }

  public enum InnerRoom {
    [pbr::OriginalName("INNER_ROOM_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("INNER_ROOM_TREASURY")] Treasury = 1,
    [pbr::OriginalName("INNER_ROOM_SANCTUM")] Sanctum = 2,
    [pbr::OriginalName("INNER_ROOM_CRYPTS")] Crypts = 3,
  }

  #endregion

  #region Messages
  public sealed partial class CardId : pb::IMessage<CardId>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CardId> _parser = new pb::MessageParser<CardId>(() => new CardId());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CardId> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Spelldawn.Protos.GamePrimitivesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CardId() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CardId(CardId other) : this() {
      switch (other.CardIdCase) {
        case CardIdOneofCase.IdentityCard:
          IdentityCard = other.IdentityCard;
          break;
        case CardIdOneofCase.Value:
          Value = other.Value;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CardId Clone() {
      return new CardId(this);
    }

    /// <summary>Field number for the "identity_card" field.</summary>
    public const int IdentityCardFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Spelldawn.Protos.PlayerName IdentityCard {
      get { return cardIdCase_ == CardIdOneofCase.IdentityCard ? (global::Spelldawn.Protos.PlayerName) cardId_ : global::Spelldawn.Protos.PlayerName.Unspecified; }
      set {
        cardId_ = value;
        cardIdCase_ = CardIdOneofCase.IdentityCard;
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Value {
      get { return cardIdCase_ == CardIdOneofCase.Value ? (int) cardId_ : 0; }
      set {
        cardId_ = value;
        cardIdCase_ = CardIdOneofCase.Value;
      }
    }

    private object cardId_;
    /// <summary>Enum of possible cases for the "card_id" oneof.</summary>
    public enum CardIdOneofCase {
      None = 0,
      IdentityCard = 1,
      Value = 2,
    }
    private CardIdOneofCase cardIdCase_ = CardIdOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CardIdOneofCase CardIdCase {
      get { return cardIdCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearCardId() {
      cardIdCase_ = CardIdOneofCase.None;
      cardId_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CardId);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CardId other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdentityCard != other.IdentityCard) return false;
      if (Value != other.Value) return false;
      if (CardIdCase != other.CardIdCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (cardIdCase_ == CardIdOneofCase.IdentityCard) hash ^= IdentityCard.GetHashCode();
      if (cardIdCase_ == CardIdOneofCase.Value) hash ^= Value.GetHashCode();
      hash ^= (int) cardIdCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (cardIdCase_ == CardIdOneofCase.IdentityCard) {
        output.WriteRawTag(8);
        output.WriteEnum((int) IdentityCard);
      }
      if (cardIdCase_ == CardIdOneofCase.Value) {
        output.WriteRawTag(16);
        output.WriteInt32(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (cardIdCase_ == CardIdOneofCase.IdentityCard) {
        output.WriteRawTag(8);
        output.WriteEnum((int) IdentityCard);
      }
      if (cardIdCase_ == CardIdOneofCase.Value) {
        output.WriteRawTag(16);
        output.WriteInt32(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (cardIdCase_ == CardIdOneofCase.IdentityCard) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) IdentityCard);
      }
      if (cardIdCase_ == CardIdOneofCase.Value) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CardId other) {
      if (other == null) {
        return;
      }
      switch (other.CardIdCase) {
        case CardIdOneofCase.IdentityCard:
          IdentityCard = other.IdentityCard;
          break;
        case CardIdOneofCase.Value:
          Value = other.Value;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            cardId_ = input.ReadEnum();
            cardIdCase_ = CardIdOneofCase.IdentityCard;
            break;
          }
          case 16: {
            Value = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            cardId_ = input.ReadEnum();
            cardIdCase_ = CardIdOneofCase.IdentityCard;
            break;
          }
          case 16: {
            Value = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RoomId : pb::IMessage<RoomId>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RoomId> _parser = new pb::MessageParser<RoomId>(() => new RoomId());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RoomId> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Spelldawn.Protos.GamePrimitivesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoomId() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoomId(RoomId other) : this() {
      switch (other.RoomIdCase) {
        case RoomIdOneofCase.InnerRoom:
          InnerRoom = other.InnerRoom;
          break;
        case RoomIdOneofCase.OuterRoom:
          OuterRoom = other.OuterRoom;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoomId Clone() {
      return new RoomId(this);
    }

    /// <summary>Field number for the "inner_room" field.</summary>
    public const int InnerRoomFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Spelldawn.Protos.InnerRoom InnerRoom {
      get { return roomIdCase_ == RoomIdOneofCase.InnerRoom ? (global::Spelldawn.Protos.InnerRoom) roomId_ : global::Spelldawn.Protos.InnerRoom.Unspecified; }
      set {
        roomId_ = value;
        roomIdCase_ = RoomIdOneofCase.InnerRoom;
      }
    }

    /// <summary>Field number for the "outer_room" field.</summary>
    public const int OuterRoomFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int OuterRoom {
      get { return roomIdCase_ == RoomIdOneofCase.OuterRoom ? (int) roomId_ : 0; }
      set {
        roomId_ = value;
        roomIdCase_ = RoomIdOneofCase.OuterRoom;
      }
    }

    private object roomId_;
    /// <summary>Enum of possible cases for the "room_id" oneof.</summary>
    public enum RoomIdOneofCase {
      None = 0,
      InnerRoom = 1,
      OuterRoom = 2,
    }
    private RoomIdOneofCase roomIdCase_ = RoomIdOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoomIdOneofCase RoomIdCase {
      get { return roomIdCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearRoomId() {
      roomIdCase_ = RoomIdOneofCase.None;
      roomId_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RoomId);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RoomId other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InnerRoom != other.InnerRoom) return false;
      if (OuterRoom != other.OuterRoom) return false;
      if (RoomIdCase != other.RoomIdCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (roomIdCase_ == RoomIdOneofCase.InnerRoom) hash ^= InnerRoom.GetHashCode();
      if (roomIdCase_ == RoomIdOneofCase.OuterRoom) hash ^= OuterRoom.GetHashCode();
      hash ^= (int) roomIdCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (roomIdCase_ == RoomIdOneofCase.InnerRoom) {
        output.WriteRawTag(8);
        output.WriteEnum((int) InnerRoom);
      }
      if (roomIdCase_ == RoomIdOneofCase.OuterRoom) {
        output.WriteRawTag(16);
        output.WriteInt32(OuterRoom);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (roomIdCase_ == RoomIdOneofCase.InnerRoom) {
        output.WriteRawTag(8);
        output.WriteEnum((int) InnerRoom);
      }
      if (roomIdCase_ == RoomIdOneofCase.OuterRoom) {
        output.WriteRawTag(16);
        output.WriteInt32(OuterRoom);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (roomIdCase_ == RoomIdOneofCase.InnerRoom) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) InnerRoom);
      }
      if (roomIdCase_ == RoomIdOneofCase.OuterRoom) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OuterRoom);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RoomId other) {
      if (other == null) {
        return;
      }
      switch (other.RoomIdCase) {
        case RoomIdOneofCase.InnerRoom:
          InnerRoom = other.InnerRoom;
          break;
        case RoomIdOneofCase.OuterRoom:
          OuterRoom = other.OuterRoom;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            roomId_ = input.ReadEnum();
            roomIdCase_ = RoomIdOneofCase.InnerRoom;
            break;
          }
          case 16: {
            OuterRoom = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            roomId_ = input.ReadEnum();
            roomIdCase_ = RoomIdOneofCase.InnerRoom;
            break;
          }
          case 16: {
            OuterRoom = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TargetId : pb::IMessage<TargetId>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TargetId> _parser = new pb::MessageParser<TargetId>(() => new TargetId());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TargetId> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Spelldawn.Protos.GamePrimitivesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TargetId() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TargetId(TargetId other) : this() {
      switch (other.TargetCase) {
        case TargetOneofCase.CardId:
          CardId = other.CardId.Clone();
          break;
        case TargetOneofCase.RoomId:
          RoomId = other.RoomId.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TargetId Clone() {
      return new TargetId(this);
    }

    /// <summary>Field number for the "card_id" field.</summary>
    public const int CardIdFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Spelldawn.Protos.CardId CardId {
      get { return targetCase_ == TargetOneofCase.CardId ? (global::Spelldawn.Protos.CardId) target_ : null; }
      set {
        target_ = value;
        targetCase_ = value == null ? TargetOneofCase.None : TargetOneofCase.CardId;
      }
    }

    /// <summary>Field number for the "room_id" field.</summary>
    public const int RoomIdFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Spelldawn.Protos.RoomId RoomId {
      get { return targetCase_ == TargetOneofCase.RoomId ? (global::Spelldawn.Protos.RoomId) target_ : null; }
      set {
        target_ = value;
        targetCase_ = value == null ? TargetOneofCase.None : TargetOneofCase.RoomId;
      }
    }

    private object target_;
    /// <summary>Enum of possible cases for the "target" oneof.</summary>
    public enum TargetOneofCase {
      None = 0,
      CardId = 1,
      RoomId = 2,
    }
    private TargetOneofCase targetCase_ = TargetOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TargetOneofCase TargetCase {
      get { return targetCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTarget() {
      targetCase_ = TargetOneofCase.None;
      target_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TargetId);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TargetId other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CardId, other.CardId)) return false;
      if (!object.Equals(RoomId, other.RoomId)) return false;
      if (TargetCase != other.TargetCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (targetCase_ == TargetOneofCase.CardId) hash ^= CardId.GetHashCode();
      if (targetCase_ == TargetOneofCase.RoomId) hash ^= RoomId.GetHashCode();
      hash ^= (int) targetCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (targetCase_ == TargetOneofCase.CardId) {
        output.WriteRawTag(10);
        output.WriteMessage(CardId);
      }
      if (targetCase_ == TargetOneofCase.RoomId) {
        output.WriteRawTag(18);
        output.WriteMessage(RoomId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (targetCase_ == TargetOneofCase.CardId) {
        output.WriteRawTag(10);
        output.WriteMessage(CardId);
      }
      if (targetCase_ == TargetOneofCase.RoomId) {
        output.WriteRawTag(18);
        output.WriteMessage(RoomId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (targetCase_ == TargetOneofCase.CardId) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CardId);
      }
      if (targetCase_ == TargetOneofCase.RoomId) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoomId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TargetId other) {
      if (other == null) {
        return;
      }
      switch (other.TargetCase) {
        case TargetOneofCase.CardId:
          if (CardId == null) {
            CardId = new global::Spelldawn.Protos.CardId();
          }
          CardId.MergeFrom(other.CardId);
          break;
        case TargetOneofCase.RoomId:
          if (RoomId == null) {
            RoomId = new global::Spelldawn.Protos.RoomId();
          }
          RoomId.MergeFrom(other.RoomId);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Spelldawn.Protos.CardId subBuilder = new global::Spelldawn.Protos.CardId();
            if (targetCase_ == TargetOneofCase.CardId) {
              subBuilder.MergeFrom(CardId);
            }
            input.ReadMessage(subBuilder);
            CardId = subBuilder;
            break;
          }
          case 18: {
            global::Spelldawn.Protos.RoomId subBuilder = new global::Spelldawn.Protos.RoomId();
            if (targetCase_ == TargetOneofCase.RoomId) {
              subBuilder.MergeFrom(RoomId);
            }
            input.ReadMessage(subBuilder);
            RoomId = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Spelldawn.Protos.CardId subBuilder = new global::Spelldawn.Protos.CardId();
            if (targetCase_ == TargetOneofCase.CardId) {
              subBuilder.MergeFrom(CardId);
            }
            input.ReadMessage(subBuilder);
            CardId = subBuilder;
            break;
          }
          case 18: {
            global::Spelldawn.Protos.RoomId subBuilder = new global::Spelldawn.Protos.RoomId();
            if (targetCase_ == TargetOneofCase.RoomId) {
              subBuilder.MergeFrom(RoomId);
            }
            input.ReadMessage(subBuilder);
            RoomId = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
